### ISSUE TITLE
action_type question

### ISSUE THREAD

**Issue by shindig21** [fredericharnois/facebook-ads-reporting-google-apps-script#4]
Hello,

Great script, thank you so much.

I'm having a problem getting specific actions out to Sheets.  I'm effectively passing this to FB through your script:

/insights?level=ad&fields=campaign_name,adset_name,ad_name,actions&action_breakdowns=action_type&filtering=[{"field":"action_type","operator":"IN","value":["link_click"]}]

Which builds the CSV with every single possible action as columns and Sheets throws the following:

"This action would increase the number of cells in the workbook above the limit of 5000000 cells. (line 48, file "get-facebook-report")"

Presume this isn't intended behaviour on FB's part and I'm being moronic?

Thanks

**Comment by fredericharnois** [comment]
Hi @shindig21!

If I understand correctly the only metric you're trying to extract is the number of link clicks each of your ads drove?

If so, try passing this instead:

/insights?level=ad&fields=campaign_name,adset_name,ad_name,inline_link_clicks

There shouldn't be a need to add the filtering part in this case.

Let me know if you were trying to do something else.

Thanks!

**Comment by shindig21** [comment]
Hi,

Thanks for your answer!

I was looking to pull all sorts of custom conversions and other actions.

Would you say the only way to do this to switch the request to a GET and parse the JSON?

Thanks!

**Comment by fredericharnois** [comment]
Oh ok, it depends then.

Say you wanted to report on purchases, your request would look like this:

/insights?level=ad&fields=campaign_name,adset_name,ad_name,actions&action_breakdowns=action_type&filtering=[{'field':'action_type','operator':'IN','value':['offsite_conversion.fb_pixel_purchase','link_click']}]

The CSV's header would have all the possible actions but only the Website Purchases and Website Purchases Conversion Value columns would actually be populated.

If that still is over 5,000,000 cells, I'm not sure that parsing the requests directly vs. running your report asynchronously is going to solve the issue as there aren't many extraneous columns being populated in the CSV. For that amount of data you might want to look into Google Cloud Storage depending on what you're doing with it afterwards.

That being said, if you're interested in pursuing parsing the JSON directly, that's how the [first versions](https://github.com/fredericharnois/facebook-ads-reporting-google-apps-script/blob/58a18e5f7a22162e10343ddac1c4cb045d9b43f1/facebook-ads-google-sheets.js) of this script worked. It tended to time out since it was adding rows one at a time. If I were to go back to that method (and I just might at one point), I'd build my arrays to be columns instead of rows.

Let me know if you have any other questions,

Thanks!
