### ISSUE TITLE
Could not parse text. (line 47, file "get-facebook-report.js")

### ISSUE THREAD

**Issue by T-Carlile** [fredericharnois/facebook-ads-reporting-google-apps-script#8]
Hi there Frederic,

Thank you for providing the script, very useful however I'm encountering the below error when running get-facebook-report.js

![screenshot](https://user-images.githubusercontent.com/60176364/72884095-7117d080-3cfd-11ea-9abd-7fcf65b2f523.jpg)

The script appears to run when TIME_INCREMENT is set to '90' in request-facebook-report.gs as below but fails if set to '1' 

![image](https://user-images.githubusercontent.com/60176364/72884316-d7045800-3cfd-11ea-83e7-da83e81d24c2.png)

Any help would be greatly appreciated!

Many thanks,
Tom

**Comment by fredericharnois** [comment]
Hi @T-Carlile,

Glad the script is useful to you!

1. How long are you waiting between the execution of request-facebook-report.js and get-facebook-report.js? When setting the increment to 1 I'd wait 5-10 minutes between the two since it may take a while for the report job to complete.
2. If you set the date range to something shorter, do you get the same error?

Thanks!

**Comment by T-Carlile** [comment]
Hi Frederic,

Thanks for the prompt reply, it appears that I was just being impatient it worked after a bit of a wait! On another note how would I go about pulling in FB custom conversions into this report, is it fairly straightforward?

Many thanks,
Tom

**Comment by fredericharnois** [comment]
No problem!

I've never done it myself but according to the [documentation](https://developers.facebook.com/docs/marketing-api/reference/ads-action-stats/) you should be able to by filtering by the following `action_type`: `offsite_conversion.custom.<custom_conv_id>`.

Let me know if that works!
